#define BOOTMAGIC_KEY_SALT KC_ENT

#define MOUSEKEY_DELAY 200
#define MOUSEKEY_INTERVAL 17
#define MOUSEKEY_MAX_SPEED 3
#define MOUSEKEY_TIME_TO_MAX 120
#define MOUSEKEY_WHEEL_MAX_SPEED 8
#define MOUSEKEY_WHEEL_TIME_TO_MAX 40

#define TAPPING_TOGGLE 3

#define PERMISSIVE_HOLD

#define LEADER_TIMEOUT 500
#define LEADER_PER_KEY_TIMING
