#define BOOTMAGIC_KEY_SALT KC_ENT

#define MOUSEKEY_DELAY             200
#define MOUSEKEY_INTERVAL          50
#define MOUSEKEY_MAX_SPEED         7
#define MOUSEKEY_TIME_TO_MAX       20
#define MOUSEKEY_WHEEL_MAX_SPEED   8
#define MOUSEKEY_WHEEL_TIME_TO_MAX 40

#define TAPPING_TOGGLE             3
